title: Miralem 的博客
subtitle: Miralemi siheeriiniith
description: 黑龙江省双鸭山市宝清县东方红林场职业棕熊，每周一三五出摊
keywords: null
author: Miralem
language: zh-CN
timezone: Asia/Shanghai
url: 'http://yoursite.com'
root: /
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: null
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
per_page: 10
pagination_dir: page
theme: next-reload
deploy:
  type: git
  repo: 'https://github.com/skhlnt/skhlnt.github.io.git'
  branch: master
  repository: 'git@github.com:skhlnt/skhlnt.github.io'
markdown_it_plus:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: “”‘’
  plugins:
    - markdown-it-katex
    - markdown-it-footnote
    - markdown-it-abbr
    - markdown-it-cjk-breaks
    - markdown-it-deflist
    - markdown-it-emoji
    - markdown-it-ins
    - markdown-it-mark
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-checkbox
    - markdown-it-imsize
    - markdown-it-expandable
  anchors:
    level: 2
    collisionSuffix: v
    permalink: true
    permalinkClass: header-anchor
    permalinkSide: left
    permalinkSymbol: ¶
search:
  path: search.xml
  field: post
  content: true
  format: html
theme_config:
  scheme: Pisces
  darkmode: false
  favicon:
    small: /images/favicon-16x16-placid.png
    medium: /images/favicon-32x32-placid.png
    apple_touch_icon: /images/apple-touch-icon-placid.png
    safari_pinned_tab: /images/logo.svg
  custom_logo: null
  creative_commons:
    license: by-nc-sa
    size: small
    sidebar: false
    post: false
    language: null
  open_graph:
    enable: true
    options: null
  menu:
    home: / || fa fa-home
    about: /about/ || fa fa-user
    tags: /tags/ || fa fa-tags
    categories: /categories/ || fa fa-th
    archives: /archives/ || fa fa-archive
  menu_settings:
    icons: true
    badges: false
  sidebar:
    position: left
    display: post
    padding: 18
    offset: 12
  avatar:
    url: >-
      https://github.com/skhlnt/skhlnt.github.io/blob/hexo/source/images/apple-touch-icon-placid.png?raw=true
    rounded: false
    rotated: false
  site_state: true
  social:
    E-Mail: 'mailto:wzh41807@126.com || fa fa-envelope'
    Zhihu: 'https://www.zhihu.com/people/di-ba-la-33 || fa fa-envelope'
  social_icons:
    enable: true
    icons_only: false
    transition: false
  links_settings:
    icon: null
    title: Links
    layout: block
  links:
    Sean Carroll: 'https://www.preposterousuniverse.com/blog/'
    Andrew Sun: 'http://www.andrewsun.net/panta_rhei/'
    3-toed sloth: 'http://bactra.org/weblog/'
    Coldison: 'https://coldison.github.io/'
    Swampy: 'https://swampy.io/'
  toc:
    enable: true
    number: true
    wrap: false
    expand_all: true
    max_depth: 6
  language_switcher: false
  footer:
    since: 2019
    icon:
      name: fa fa-copyright
      animated: false
      color: '#808080'
    copyright: Miralem - 允许一切带引用的转载
    powered: false
    beian:
      enable: false
      icp: null
      gongan_id: null
      gongan_num: null
      gongan_icon_url: null
  excerpt_description: true
  read_more_btn: true
  post_meta:
    item_text: true
    created_at: true
    updated_at:
      enable: true
      another_day: true
    categories: true
  symbols_count_time:
    separated_meta: true
    item_text_total: true
  tag_icon: false
  reward_settings:
    enable: false
    animation: false
  reward: null
  follow_me: null
  related_posts:
    enable: false
    title: null
    display_in_home: false
  post_edit:
    enable: false
    url: 'https://github.com/user-name/repo-name/tree/branch-name/subdirectory-name/'
  post_navigation: left
  tagcloud:
    min: 12
    max: 30
    amount: 200
    orderby: name
    order: 1
  calendar:
    calendar_id: <required>
    api_key: <required>
    orderBy: startTime
    showLocation: false
    offsetMax: 72
    offsetMin: 4
    showDeleted: false
    singleEvents: true
    maxResults: 250
  preconnect: false
  text_align:
    desktop: justify
    mobile: justify
  mobile_layout_economy: false
  theme_color:
    light: '#222'
    dark: '#222'
  body_scrollbar:
    overlay: false
    stable: false
  codeblock:
    theme:
      light: default
      dark: stackoverflow-dark
    prism:
      light: prism
      dark: prism-dark
    copy_button:
      enable: false
      style: null
  back2top:
    enable: true
    sidebar: false
    scrollpercent: true
  reading_progress:
    enable: false
    start_at: left
    position: top
    reversed: false
    color: '#37c6c0'
    height: 3px
  bookmark:
    enable: true
    color: '#222'
    save: auto
  github_banner:
    enable: false
    permalink: 'https://github.com/yourname'
    title: Follow me on GitHub
  font:
    enable: true
    host: 'https://fonts.loli.net'
    global:
      external: true
      family: Noto Serif SC
      size: null
    title:
      external: true
      family: Noto Serif SC
      size: null
    headings:
      external: true
      family: null
      size: null
    posts:
      external: true
      family: Noto Serif SC
    codes:
      external: true
      family: Source Code Pro
  index_with_subtitle: false
  exturl: false
  exturl_icon: true
  google_site_verification: null
  bing_site_verification: null
  yandex_site_verification: null
  baidu_site_verification: null
  math:
    every_page: false
    mathjax:
      enable: false
      tags: none
    katex:
      enable: true
      cdn: 'https://cdnjs.loli.net/ajax/libs/KaTeX/0.10.2/katex.min.css'
      copy_tex: true
  pjax: false
  fancybox: false
  mediumzoom: false
  lazyload: false
  pangu: false
  quicklink:
    enable: false
    home: false
    archive: false
    delay: true
    timeout: 3000
    priority: true
  comments:
    style: tabs
    active: null
    storage: true
    lazyload: false
    nav: null
  waline:
    enable: true
    serverURL: waline-server-phi.vercel.app
    placeholder: 请文明评论呀
    GRAVATAR_URL: 'https://seccdn.libravatar.org/gravatarproxy/{{mail|md5}}?s=80'
    meta:
      - nick
      - mail
      - link
    pageSize: 10
    lang: zh-cn
    visitor: false
    comment_count: true
    requiredFields: []
    libUrl: null
  disqus:
    enable: false
    shortname: null
    count: true
  disqusjs:
    enable: false
    api: null
    apikey: null
    shortname: null
  changyan:
    enable: false
    appid: null
    appkey: null
  livere_uid: null
  gitalk:
    enable: false
    github_id: null
    repo: null
    client_id: null
    client_secret: null
    admin_user: null
    distraction_free_mode: true
    proxy: >-
      https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token
    language: null
  utterances:
    enable: false
    repo: user-name/repo-name
    issue_term: pathname
    theme: github-light
  isso: null
  rating:
    enable: false
    id: null
    color: '#fc6423'
  add_this_id: null
  google_analytics:
    tracking_id: null
    only_pageview: false
  baidu_analytics: null
  growingio_analytics: null
  cloudflare_analytics: null
  clarity_analytics: null
  leancloud_visitors:
    enable: false
    app_id: null
    app_key: null
    server_url: null
    security: true
  firestore:
    enable: false
    collection: articles
    apiKey: null
    projectId: null
  busuanzi_count:
    enable: false
    total_visitors: true
    total_visitors_icon: fa fa-user
    total_views: true
    total_views_icon: fa fa-eye
    post_views: true
    post_views_icon: far fa-eye
  algolia_search:
    enable: false
    hits:
      per_page: 10
  local_search:
    enable: true
    trigger: auto
    top_n_per_article: 1
    unescape: false
    preload: false
  chat:
    enable: false
    icon: fa fa-comment
    text: Chat
  chatra:
    enable: false
    async: true
    id: null
  tidio:
    enable: false
    key: null
  gitter:
    enable: false
    room: null
  note:
    style: flat
    icons: false
    light_bg_offset: 0
  tabs:
    sticky: false
    transition:
      tabs: false
      labels: true
  pdf:
    enable: false
    height: 500px
  mermaid:
    enable: false
    theme:
      light: default
      dark: dark
  motion:
    enable: true
    async: false
    transition:
      post_block: fadeIn
      post_header: fadeInDown
      post_body: fadeInDown
      coll_header: fadeInLeft
      sidebar: fadeInUp
  pace:
    enable: false
    color: blue
    theme: minimal
  canvas_ribbon:
    enable: false
    size: 300
    alpha: 0.6
    zIndex: -1
  vendors:
    internal: local
    plugins: local
  css: css
  js: js
  images: images
